### ISSUE TITLE
Pitrezor port for orangepi one

### ISSUE THREAD

**Issue by s-mohammad-dabir** [heneault/yocto-pitrezor#1]
Hey,
Thank you for your awesome job. It's very intresting.
I'm intrested in porting pitrezor for orangepi (allwinner H3) devices. Will you plan to do this in future? If no, so how can I do it by myself?
Regards

**Comment by heneault** [comment]
I have no plan right now to do this since I don't have this board in my hand. You could probably add the bsp and kernel yocto layer that match your board and modify the local.conf to use it.
