### ISSUE TITLE
Trezor firmware 1.9.4

### ISSUE THREAD

**Issue by TypeVII** [heneault/yocto-pitrezor#10]
Care to push an update?

**Comment by heneault** [comment]
Yes I am working on that. I expect to finish it next week. I am updating the whole platform too

**Comment by iTzNikolovich** [comment]
Hi friend... First of all thanks for what you have made available... I have a question; When the update is released, will we lose our data and need to use the recovery keys? @TypeVII

**Comment by TypeVII** [comment]
@iTzNikolovich That is correct.

**Comment by heneault** [comment]
update is released!. Yes after flashing your sd card, you have to redo the configuration in the pitrezor.config file an then recover your wallet with your seed
