### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by filipenobrerc** [heneault/yocto-pitrezor#13]
Unable to build sudo ./build-pitrezor.sh 1.10.0.0 raspberrypi0-wifi on MacOS Catalina.

Error:
| {standard input}: Assembler messages:
| {standard input}:26318: Warning: end of file not at end of a line; newline inserted
| {standard input}:27175: Error: unknown pseudo-op: `.cfi_'
| {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
| g++: fatal error: Killed signal terminated program cc1plus
| compilation terminated.
| make[4]: *** [Makefile:1137: powerpc.o] Error 1
| make[4]: *** Waiting for unfinished jobs....
| make[4]: Leaving directory '/home/build/yocto-pitrezor/build/tmp/work/x86_64-linux/binutils-cross-arm/2.34-r0/git/build.x86_64-linux.arm-poky-linux-gnueabi/gold'
| make[3]: *** [Makefile:1156: all-recursive] Error 1
| make[3]: Leaving directory '/home/build/yocto-pitrezor/build/tmp/work/x86_64-linux/binutils-cross-arm/2.34-r0/git/build.x86_64-linux.arm-poky-linux-gnueabi/gold'
| make[2]: *** [Makefile:896: all] Error 2
| make[2]: Leaving directory '/home/build/yocto-pitrezor/build/tmp/work/x86_64-linux/binutils-cross-arm/2.34-r0/git/build.x86_64-linux.arm-poky-linux-gnueabi/gold'
| make[1]: *** [Makefile:6102: all-gold] Error 2
| make[1]: Leaving directory '/home/build/yocto-pitrezor/build/tmp/work/x86_64-linux/binutils-cross-arm/2.34-r0/git/build.x86_64-linux.arm-poky-linux-gnueabi'
| make: *** [Makefile:853: all] Error 2
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/home/build/yocto-pitrezor/build/../poky/meta/recipes-devtools/binutils/binutils-cross_2.34.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 436 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/build/yocto-pitrezor/build/../poky/meta/recipes-devtools/binutils/binutils-cross_2.34.bb:do_compile

**Comment by heneault** [comment]
can you try in a linux vm running on mac ?

**Comment by filipenobrerc** [comment]
Sure. I will try that. Thank you.

**Comment by filipenobrerc** [comment]
Yes I will try that.

Also, can you please tell me what modifications I need to do in order to build trezor T firmware instead?


Thank you.
