### ISSUE TITLE
Is possible to add SD Card partition for saving files ?

### ISSUE THREAD

**Issue by Chuck3CZ** [heneault/yocto-pitrezor#16]
Is possible to add SD Card partition for saving on large cards, like saving files/passwords for password manager, etc. 
With g_mass_storage driver.

**Comment by heneault** [comment]
I think it would be possible would require change to the usb configuration to support this interface and kernel module at the time as the pitrezor. However, what I would suggest is to look at the U2F functionality. This is something already supported and can be used to handle password properly.
Also, providing access for the host to access the SD card is a potential risk to open a security hole
