### ISSUE TITLE
qemu URL

### ISSUE THREAD

**Issue by segunda** [heneault/yocto-pitrezor#2]
My installation keeps crashing on:
'ERROR: qemu-native-2.10.0-r0 do_unpack: Unpack failure for URL: 'http://wiki.qemu-project.org/download/qemu-2.10.0.tar.bz2'. Unpack command PATH="/home/build/...'

Shouldn't the URL be something like:
https://download.qemu.org/qemu-2.10.0.tar.bz2

**Comment by heneault** [comment]
Maybe a bad download ? You can issue the 2 following commands in your bitbake environment to try to clean your last download and restart a download/unpack : 

`bitbake -f -c cleanall qemu-native`
`bitbake -f -c unpack qemu-native`

**Comment by segunda** [comment]
Hi, thanks for the reply ! it is a bad download, the URL on the server has changed.
I'm fairly new to this and not shure where to change it.
I did manage to install qemu via Brew. This lets the script continue a bit further.
I added libPng, and libMpc in the same manner.
Unfortunately I don't seem to have bitbake installed, going through yocto setup now...

**Comment by heneault** [comment]
no problem. You can check the build script and the docker file if you want to start hacking yocto/bitbake to setup a custom environment.
