### ISSUE TITLE
Compile from Source Code

### ISSUE THREAD

**Issue by StingJohnson** [heneault/yocto-pitrezor#21]
Hi, 
i wanted to build from source code and i git cloned and ran the build script. It turned out that the compiled zip file has a different hash than the pre-built binary file.
Would you let me know what can be the issue?

**Comment by heneault** [comment]
I suspect that could be the date of each file. The compiler probably use the current date each time it generate the files so that could explain the difference at the file system level. Did you try to binary compare both tree side by side ?
