### ISSUE TITLE
USB Device not Recognized

### ISSUE THREAD

**Issue by honzapatCZ** [heneault/yocto-pitrezor#5]
Tried 3 different PCs, 4 different usb cables, Windows always shows "The latest USB device you plugged in could not be recognized" usbdevview shows that the HID descriptor failed.
Might be a problem with my Pi zero, but I dont know how could I caused it(and more importantly how to fix it).

**Comment by heneault** [comment]
This look like a bad pi zero to me. I think you need a replacement.

You could try to setup the pi as a usb gadget to experiment a different setup: https://gist.github.com/gbaman/50b6cca61dd1c3f88f41

**Comment by honzapatCZ** [comment]
Probably, ordered 2 new ones

**Comment by honzapatCZ** [comment]
Yes it was. Works like a charm now.
