### ISSUE TITLE
Waveshare oled LCD 1.3 issue with windows 7/10 and linux

### ISSUE THREAD

**Issue by mccolister1017** [heneault/yocto-pitrezor#7]
hello just got a problem with linux windows and every computer i touch , the screen is ok configuration is ok but the pitrezor is not detected on any computer . same error Connect your Trezor to continue. new cable usb didn't change anyting the screen is good but the pizero is not detected

**Comment by mccolister1017** [comment]
im on the  last firmware btw

**Comment by heneault** [comment]
some things to check:
- make sure the usb cable is connected in the proper usb port of the pi zero (refer to image)
- try to use the wallet with the latest version of chrome.
- try to install the trezor bridge
- make sure your usb cable can transfer data.
- try different usb ports on the computer (front/back)
- to make sure it this not an hardware issue, you can try the standard raspberry pi image configured as a usb network connection : https://www.instructables.com/id/Raspberry-Pi-Zero-USB-Dongle/
