### ISSUE TITLE
pizero 1.3 

### ISSUE THREAD

**Issue by mccolister1017** [heneault/yocto-pitrezor#8]
Hello I just noticed that something is wrong with the firmware. It's OK with my pizero WH but won't work with the pizero 1.3

**Comment by mccolister1017** [comment]
all firmeware i think something is wrong with the firmware

**Comment by heneault** [comment]
Are you talking about the Oled ? Which model/manufacturer ?

**Comment by mccolister1017** [comment]
NO the oled is ok it's just the Raspberry pizero himself tested with 2 pizero model 1.3 not working but everything is ok with the Pizero WH .

**Comment by mccolister1017** [comment]
i think it's an issue with the firmware or am i wrong .
